### ISSUE TITLE
Script Never GITs Fuse-EXT2 Source

### ISSUE THREAD

**Issue by bsom** [ipatch/fuse-ext2#2]
The script "macos-build-fuse-ext2-v0.0.10.sh" never downloads the actual source for Fuse-EXT2 from your Git repository.

**Comment by ipatch** [comment]
@bsom 

Somehow I never got a notification for this issue 🤦‍♀️

Anyways, how I use the script is to clone the repo, cd in the **build** dir then run the script from that dir, and then manually install because it requires **sudo** to install for the time being.

```shell
git clone https://github.com/ipatch/fuse-ext2
cd fuse-ext2
cd build
./macos-build-fuse-ext2-v0.0.10.sh
```

I hope those instructions help you out.
